// Generated by webapp/build_doctors_js.py — do not edit by hand.
// Public data only (slug + name). Credentials live server-side in doctors/.
window.DOCTORS = {
  "nitin": {
    "name": "Nitin Jagtap"
  },
  "krithi": {
    "name": "Krithi"
  },
  "vilas": {
    "name": "Vilas Biradar"
  },
  "hardik": {
    "name": "Hardik Rughwani"
  },
  "aniruddha": {
    "name": "Aniruddha Pratap Singh"
  },
  "rakesh": {
    "name": "Rakesh Garlapati"
  }
};
