// Generated by webapp/build_kg_json.py — do not edit by hand.
window.KG_DATA = {
  "version": "v4",
  "entry_question": "q_main_complaint",
  "questions": {
    "q_main_complaint": {
      "id": "q_main_complaint",
      "text": "What problems are you having today?",
      "type": "multi_choice",
      "options": [
        {
          "value": "abdominal_pain",
          "label": "Abdominal / Tummy Pain"
        },
        {
          "value": "heartburn",
          "label": "Heartburn / Acid Reflux"
        },
        {
          "value": "dysphagia",
          "label": "Difficulty Swallowing"
        },
        {
          "value": "nausea_vomiting",
          "label": "Nausea / Vomiting"
        },
        {
          "value": "dyspepsia",
          "label": "Indigestion / Bloating"
        },
        {
          "value": "belching",
          "label": "Belching / Wind"
        },
        {
          "value": "diarrhoea",
          "label": "Loose Motions / Diarrhoea"
        },
        {
          "value": "constipation",
          "label": "Constipation"
        },
        {
          "value": "jaundice",
          "label": "Yellowing of Eyes or Skin"
        },
        {
          "value": "rectal_bleeding",
          "label": "Bleeding from the Back Passage"
        },
        {
          "value": "perianal",
          "label": "Pain / Lump Around the Back Passage"
        },
        {
          "value": "faecal_incontinence",
          "label": "Trouble Controlling the Bowels"
        },
        {
          "value": "bloating",
          "label": "Bloating / Swollen Tummy"
        },
        {
          "value": "ascites",
          "label": "Tummy Swelling with Fluid"
        },
        {
          "value": "weight_loss",
          "label": "Losing Weight"
        },
        {
          "value": "anaemia",
          "label": "Tiredness / Looking Pale"
        },
        {
          "value": "anorexia",
          "label": "Loss of Appetite"
        }
      ]
    },
    "ap_duration": {
      "id": "ap_duration",
      "text": "How long have you had this pain?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1w",
          "label": "Less than a week",
          "hpi": "less than a week"
        },
        {
          "value": "1_4w",
          "label": "1–4 weeks",
          "hpi": "one to four weeks"
        },
        {
          "value": "1_6m",
          "label": "1–6 months",
          "hpi": "one to six months"
        },
        {
          "value": "gt_6m",
          "label": "More than 6 months",
          "hpi": "more than six months"
        }
      ]
    },
    "ap_site": {
      "id": "ap_site",
      "text": "Where is the pain? Tap the area(s) on the picture.",
      "type": "region_select",
      "options": [
        {
          "value": "ruq",
          "region": "upper-right",
          "label": "Upper right",
          "hpi": "right upper quadrant"
        },
        {
          "value": "epigastric",
          "region": "upper-centre",
          "label": "Upper middle",
          "hpi": "epigastrium"
        },
        {
          "value": "luq",
          "region": "upper-left",
          "label": "Upper left",
          "hpi": "left upper quadrant"
        },
        {
          "value": "right_flank",
          "region": "middle-right",
          "label": "Right side",
          "hpi": "right flank"
        },
        {
          "value": "periumbilical",
          "region": "middle-centre",
          "label": "Around the navel",
          "hpi": "periumbilical region"
        },
        {
          "value": "left_flank",
          "region": "middle-left",
          "label": "Left side",
          "hpi": "left flank"
        },
        {
          "value": "rlq",
          "region": "lower-right",
          "label": "Lower right",
          "hpi": "right lower quadrant"
        },
        {
          "value": "hypogastric",
          "region": "lower-centre",
          "label": "Lower middle",
          "hpi": "suprapubic region"
        },
        {
          "value": "llq",
          "region": "lower-left",
          "label": "Lower left",
          "hpi": "left lower quadrant"
        },
        {
          "value": "diffuse",
          "region": "entire-abdomen",
          "label": "All over",
          "hpi": "diffuse abdomen"
        }
      ]
    },
    "ap_character": {
      "id": "ap_character",
      "text": "What does the pain feel like?",
      "type": "single_choice",
      "options": [
        {
          "value": "burning",
          "label": "Burning",
          "hpi": "burning"
        },
        {
          "value": "cramping",
          "label": "Cramping / comes in waves",
          "hpi": "cramping"
        },
        {
          "value": "sharp",
          "label": "Sharp",
          "hpi": "sharp"
        },
        {
          "value": "pricking",
          "label": "Pricking",
          "hpi": "pricking"
        },
        {
          "value": "dull",
          "label": "Dull ache",
          "hpi": "dull"
        }
      ]
    },
    "ap_radiation": {
      "id": "ap_radiation",
      "text": "Does the pain travel anywhere?",
      "type": "single_choice",
      "options": [
        {
          "value": "back",
          "label": "To the back",
          "hpi": "to the back"
        },
        {
          "value": "right_shoulder",
          "label": "To the right shoulder",
          "hpi": "to the right shoulder"
        },
        {
          "value": "chest",
          "label": "To the chest",
          "hpi": "to the chest"
        },
        {
          "value": "none",
          "label": "Stays in one place",
          "hpi": "nowhere"
        }
      ]
    },
    "ap_pattern": {
      "id": "ap_pattern",
      "text": "Is the pain there all the time, or does it come and go?",
      "type": "single_choice",
      "options": [
        {
          "value": "constant",
          "label": "All the time",
          "hpi": "constant"
        },
        {
          "value": "intermittent",
          "label": "Comes and goes",
          "hpi": "intermittent"
        }
      ]
    },
    "ap_meals": {
      "id": "ap_meals",
      "text": "Does eating change the pain?",
      "type": "single_choice",
      "options": [
        {
          "value": "better_eating",
          "label": "Better after eating",
          "hpi": "relieved by eating"
        },
        {
          "value": "worse_eating",
          "label": "Worse after eating",
          "hpi": "worse after eating"
        },
        {
          "value": "none",
          "label": "No change",
          "hpi": "unrelated to meals"
        }
      ]
    },
    "ap_night": {
      "id": "ap_night",
      "text": "Does the pain wake you up at night?",
      "type": "yes_no",
      "options": []
    },
    "hb_duration": {
      "id": "hb_duration",
      "text": "How long have you had heartburn?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1w",
          "label": "Less than a week",
          "hpi": "less than a week"
        },
        {
          "value": "1_4w",
          "label": "1–4 weeks",
          "hpi": "one to four weeks"
        },
        {
          "value": "1_6m",
          "label": "1–6 months",
          "hpi": "one to six months"
        },
        {
          "value": "gt_6m",
          "label": "More than 6 months",
          "hpi": "more than six months"
        }
      ]
    },
    "hb_location": {
      "id": "hb_location",
      "text": "Where do you feel the burning?",
      "type": "single_choice",
      "options": [
        {
          "value": "chest",
          "label": "Chest",
          "hpi": "chest"
        },
        {
          "value": "throat",
          "label": "Throat",
          "hpi": "throat"
        },
        {
          "value": "both",
          "label": "Both chest and throat",
          "hpi": "chest and throat"
        }
      ]
    },
    "hb_rising": {
      "id": "hb_rising",
      "text": "Does the burning rise up toward your mouth?",
      "type": "yes_no",
      "options": []
    },
    "hb_taste": {
      "id": "hb_taste",
      "text": "Do you get a sour or bitter taste in your mouth?",
      "type": "yes_no",
      "options": []
    },
    "hb_timing": {
      "id": "hb_timing",
      "text": "When does it usually happen?",
      "type": "single_choice",
      "options": [
        {
          "value": "after_meals",
          "label": "After meals",
          "hpi": "after meals"
        },
        {
          "value": "at_night",
          "label": "At night",
          "hpi": "at night"
        },
        {
          "value": "both",
          "label": "Both",
          "hpi": "after meals and at night"
        }
      ]
    },
    "hb_triggers": {
      "id": "hb_triggers",
      "text": "Which foods or drinks trigger it? (choose any)",
      "type": "multi_choice",
      "options": [
        {
          "value": "spicy",
          "label": "Spicy food"
        },
        {
          "value": "fatty",
          "label": "Fatty food"
        },
        {
          "value": "coffee",
          "label": "Coffee"
        },
        {
          "value": "alcohol",
          "label": "Alcohol"
        },
        {
          "value": "carbonated",
          "label": "Fizzy drinks"
        },
        {
          "value": "none",
          "label": "None in particular"
        }
      ]
    },
    "hb_frequency": {
      "id": "hb_frequency",
      "text": "How often does it happen?",
      "type": "single_choice",
      "options": [
        {
          "value": "daily",
          "label": "Daily",
          "hpi": "daily"
        },
        {
          "value": "weekly",
          "label": "Weekly",
          "hpi": "weekly"
        },
        {
          "value": "occasional",
          "label": "Now and then",
          "hpi": "occasionally"
        }
      ]
    },
    "hb_sleep": {
      "id": "hb_sleep",
      "text": "Does it disturb your sleep?",
      "type": "yes_no",
      "options": []
    },
    "hb_cough_voice": {
      "id": "hb_cough_voice",
      "text": "Do you have a long-standing cough or hoarse voice?",
      "type": "yes_no",
      "options": []
    },
    "hb_chest_pain": {
      "id": "hb_chest_pain",
      "text": "Do you have any chest pain?",
      "type": "yes_no",
      "options": []
    },
    "hb_chest_pain_radiate": {
      "id": "hb_chest_pain_radiate",
      "text": "Does the chest pain spread to your arm or jaw?",
      "type": "yes_no",
      "options": []
    },
    "hb_tried_meds": {
      "id": "hb_tried_meds",
      "text": "Have you tried antacids or acid-reducing medicines?",
      "type": "yes_no",
      "options": []
    },
    "hb_meds_helped": {
      "id": "hb_meds_helped",
      "text": "Did the medicines help?",
      "type": "yes_no",
      "options": []
    },
    "hb_prior_scope": {
      "id": "hb_prior_scope",
      "text": "Have you had an endoscopy or other tests before?",
      "type": "yes_no",
      "options": []
    },
    "dys_duration": {
      "id": "dys_duration",
      "text": "How long have you had difficulty swallowing?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1w",
          "label": "Less than a week",
          "hpi": "less than a week"
        },
        {
          "value": "1_4w",
          "label": "1–4 weeks",
          "hpi": "one to four weeks"
        },
        {
          "value": "1_6m",
          "label": "1–6 months",
          "hpi": "one to six months"
        },
        {
          "value": "gt_6m",
          "label": "More than 6 months",
          "hpi": "more than six months"
        }
      ]
    },
    "dys_type": {
      "id": "dys_type",
      "text": "When you swallow, does food get stuck, is it painful, or both?",
      "type": "single_choice",
      "options": [
        {
          "value": "stuck",
          "label": "Food gets stuck",
          "hpi": "food sticking"
        },
        {
          "value": "painful",
          "label": "Painful to swallow",
          "hpi": "painful swallowing"
        },
        {
          "value": "both",
          "label": "Both",
          "hpi": "food sticking and painful swallowing"
        }
      ]
    },
    "dys_consistency": {
      "id": "dys_consistency",
      "text": "Is it worse with solids, liquids, or both?",
      "type": "single_choice",
      "options": [
        {
          "value": "solids",
          "label": "Solids",
          "hpi": "solids"
        },
        {
          "value": "liquids",
          "label": "Liquids",
          "hpi": "liquids"
        },
        {
          "value": "both",
          "label": "Both",
          "hpi": "both solids and liquids"
        }
      ]
    },
    "dys_progression": {
      "id": "dys_progression",
      "text": "Is it getting worse, staying the same, or coming and going?",
      "type": "single_choice",
      "options": [
        {
          "value": "worsening",
          "label": "Getting worse",
          "hpi": "progressive"
        },
        {
          "value": "stable",
          "label": "Staying the same",
          "hpi": "stable"
        },
        {
          "value": "intermittent",
          "label": "Comes and goes",
          "hpi": "intermittent"
        }
      ]
    },
    "dys_onset": {
      "id": "dys_onset",
      "text": "Did it start suddenly or gradually?",
      "type": "single_choice",
      "options": [
        {
          "value": "sudden",
          "label": "Suddenly",
          "hpi": "sudden"
        },
        {
          "value": "gradual",
          "label": "Gradually",
          "hpi": "gradual"
        }
      ]
    },
    "dys_regurg": {
      "id": "dys_regurg",
      "text": "Do you bring up undigested food?",
      "type": "yes_no",
      "options": []
    },
    "dys_reflux": {
      "id": "dys_reflux",
      "text": "Do you also have heartburn or acid reflux?",
      "type": "yes_no",
      "options": []
    },
    "dys_aspiration": {
      "id": "dys_aspiration",
      "text": "Do you cough or choke when swallowing, especially liquids?",
      "type": "yes_no",
      "options": []
    },
    "dys_voice": {
      "id": "dys_voice",
      "text": "Has your voice changed or become hoarse?",
      "type": "yes_no",
      "options": []
    },
    "dys_radiation_hx": {
      "id": "dys_radiation_hx",
      "text": "Have you ever had radiation treatment to the chest or neck?",
      "type": "yes_no",
      "options": []
    },
    "dys_corrosive": {
      "id": "dys_corrosive",
      "text": "Have you ever swallowed a corrosive substance or had a pill injury?",
      "type": "yes_no",
      "options": []
    },
    "nv_duration": {
      "id": "nv_duration",
      "text": "How long have you had nausea or vomiting?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1w",
          "label": "Less than a week",
          "hpi": "less than a week"
        },
        {
          "value": "1_4w",
          "label": "1–4 weeks",
          "hpi": "one to four weeks"
        },
        {
          "value": "gt_1m",
          "label": "More than a month",
          "hpi": "more than a month"
        }
      ]
    },
    "nv_vomit_content": {
      "id": "nv_vomit_content",
      "text": "What does the vomit look like?",
      "type": "single_choice",
      "options": [
        {
          "value": "digested_food",
          "label": "Digested food",
          "hpi": "digested food"
        },
        {
          "value": "undigested_food",
          "label": "Undigested food",
          "hpi": "undigested food"
        },
        {
          "value": "bile",
          "label": "Yellow-green bile",
          "hpi": "bile"
        },
        {
          "value": "blood",
          "label": "Blood",
          "hpi": "blood"
        },
        {
          "value": "coffee_ground",
          "label": "Coffee-ground material",
          "hpi": "coffee-ground material"
        },
        {
          "value": "none",
          "label": "Only nausea",
          "no vomit": null,
          "hpi": "nausea without vomiting"
        }
      ]
    },
    "nv_timing": {
      "id": "nv_timing",
      "text": "When does the vomiting happen?",
      "type": "single_choice",
      "options": [
        {
          "value": "soon_after_eating",
          "label": "Soon after eating",
          "hpi": "soon after eating"
        },
        {
          "value": "hours_after_eating",
          "label": "A few hours after eating",
          "hpi": "hours after eating"
        },
        {
          "value": "unrelated",
          "label": "Not related to food",
          "hpi": "unrelated to meals"
        }
      ]
    },
    "nv_abd_pain": {
      "id": "nv_abd_pain",
      "text": "Do you also have tummy pain?",
      "type": "yes_no",
      "options": []
    },
    "nv_new_meds": {
      "id": "nv_new_meds",
      "text": "Have you started any new medicines recently?",
      "type": "yes_no",
      "options": []
    },
    "nv_travel_diet": {
      "id": "nv_travel_diet",
      "text": "Any recent travel or change in diet?",
      "type": "yes_no",
      "options": []
    },
    "dy_duration": {
      "id": "dy_duration",
      "text": "How long have you had indigestion or bloating?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1m",
          "label": "Less than a month",
          "hpi": "less than a month"
        },
        {
          "value": "1_6m",
          "label": "1–6 months",
          "hpi": "one to six months"
        },
        {
          "value": "gt_6m",
          "label": "More than 6 months",
          "hpi": "more than six months"
        }
      ]
    },
    "dy_relation": {
      "id": "dy_relation",
      "text": "When does it come on?",
      "type": "single_choice",
      "options": [
        {
          "value": "during_meals",
          "label": "During meals",
          "hpi": "during meals"
        },
        {
          "value": "after_meals",
          "label": "After meals",
          "hpi": "after meals"
        },
        {
          "value": "empty_stomach",
          "label": "On an empty stomach",
          "hpi": "on an empty stomach"
        }
      ]
    },
    "dy_food_triggers": {
      "id": "dy_food_triggers",
      "text": "Do certain foods trigger it? (choose any)",
      "type": "multi_choice",
      "options": [
        {
          "value": "wheat",
          "label": "Wheat"
        },
        {
          "value": "dairy",
          "label": "Dairy"
        },
        {
          "value": "fatty",
          "label": "Fatty food"
        },
        {
          "value": "none",
          "label": "None in particular"
        }
      ]
    },
    "dy_antacid_relief": {
      "id": "dy_antacid_relief",
      "text": "Is it relieved by antacids?",
      "type": "yes_no",
      "options": []
    },
    "dy_stool_relief": {
      "id": "dy_stool_relief",
      "text": "Is it better after you pass stool?",
      "type": "yes_no",
      "options": []
    },
    "dy_bloating": {
      "id": "dy_bloating",
      "text": "Do you feel bloated or full quickly?",
      "type": "yes_no",
      "options": []
    },
    "be_duration": {
      "id": "be_duration",
      "text": "How long have you had excessive belching?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1m",
          "label": "Less than a month",
          "hpi": "less than a month"
        },
        {
          "value": "gt_1m",
          "label": "More than a month",
          "hpi": "more than a month"
        }
      ]
    },
    "be_timing": {
      "id": "be_timing",
      "text": "When do you belch most?",
      "type": "single_choice",
      "options": [
        {
          "value": "after_meals",
          "label": "After meals",
          "hpi": "after meals"
        },
        {
          "value": "anytime",
          "label": "Any time",
          "hpi": "throughout the day"
        }
      ]
    },
    "be_fizzy_fast_stress": {
      "id": "be_fizzy_fast_stress",
      "text": "Is it worse with fizzy drinks, eating fast, or stress?",
      "type": "yes_no",
      "options": []
    },
    "be_food_triggers": {
      "id": "be_food_triggers",
      "text": "Do particular foods bring it on?",
      "type": "yes_no",
      "options": []
    },
    "be_flatulence": {
      "id": "be_flatulence",
      "text": "Do you also have a lot of flatulence or tummy rumbling?",
      "type": "yes_no",
      "options": []
    },
    "di_duration": {
      "id": "di_duration",
      "text": "How long have you had loose motions?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_2w",
          "label": "Less than 2 weeks",
          "hpi": "an acute (<2 week)"
        },
        {
          "value": "2_4w",
          "label": "2–4 weeks",
          "hpi": "a 2–4 week"
        },
        {
          "value": "gt_4w",
          "label": "More than 4 weeks",
          "hpi": "a chronic (>4 week)"
        }
      ]
    },
    "di_frequency": {
      "id": "di_frequency",
      "text": "How many times a day?",
      "type": "number",
      "options": []
    },
    "di_consistency": {
      "id": "di_consistency",
      "text": "What are the stools like?",
      "type": "single_choice",
      "options": [
        {
          "value": "mushy",
          "label": "Mushy",
          "hpi": "mushy"
        },
        {
          "value": "watery",
          "label": "Watery",
          "hpi": "watery"
        },
        {
          "value": "liquid",
          "label": "Completely liquid",
          "hpi": "liquid"
        }
      ]
    },
    "di_blood": {
      "id": "di_blood",
      "text": "Is there blood in the stool?",
      "type": "yes_no",
      "options": []
    },
    "di_mucus": {
      "id": "di_mucus",
      "text": "Is there mucus in the stool?",
      "type": "yes_no",
      "options": []
    },
    "di_nocturnal": {
      "id": "di_nocturnal",
      "text": "Does it wake you from sleep at night?",
      "type": "yes_no",
      "options": []
    },
    "di_relieved_by_defecation": {
      "id": "di_relieved_by_defecation",
      "text": "Are the cramps relieved by passing stool?",
      "type": "yes_no",
      "options": []
    },
    "di_recent_travel": {
      "id": "di_recent_travel",
      "text": "Any recent travel?",
      "type": "yes_no",
      "options": []
    },
    "di_recent_antibiotics": {
      "id": "di_recent_antibiotics",
      "text": "Any recent course of antibiotics?",
      "type": "yes_no",
      "options": []
    },
    "co_duration": {
      "id": "co_duration",
      "text": "How long have you been constipated?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1m",
          "label": "Less than a month",
          "hpi": "less than a month"
        },
        {
          "value": "1_6m",
          "label": "1–6 months",
          "hpi": "one to six months"
        },
        {
          "value": "gt_6m",
          "label": "More than 6 months",
          "hpi": "more than six months"
        }
      ]
    },
    "co_frequency": {
      "id": "co_frequency",
      "text": "How often do you pass stool?",
      "type": "single_choice",
      "options": [
        {
          "value": "once_daily",
          "label": "Once a day",
          "hpi": "once daily"
        },
        {
          "value": "alt_days",
          "label": "Every 2–3 days",
          "hpi": "every 2–3 days"
        },
        {
          "value": "once_3plus_days",
          "label": "Less than twice a week",
          "hpi": "less than twice a week"
        }
      ]
    },
    "co_urge": {
      "id": "co_urge",
      "text": "Do you feel the urge to pass stool each day?",
      "type": "yes_no",
      "options": []
    },
    "co_timing": {
      "id": "co_timing",
      "text": "When do you usually feel the urge to pass stool? (choose any)",
      "type": "multi_choice",
      "options": [
        {
          "value": "morning",
          "label": "In the morning",
          "hpi": "in the morning"
        },
        {
          "value": "after_meals",
          "label": "After meals",
          "hpi": "after meals"
        },
        {
          "value": "night",
          "label": "At night",
          "hpi": "at night"
        },
        {
          "value": "irregular",
          "label": "No fixed time",
          "hpi": "at no fixed time"
        }
      ]
    },
    "co_bristol": {
      "id": "co_bristol",
      "text": "Which stool type(s) best match yours? Choose up to 2.",
      "type": "bristol_select",
      "options": [
        {
          "value": "1",
          "label": "Type 1 — separate hard lumps",
          "hpi": "Bristol type 1 (separate hard lumps)"
        },
        {
          "value": "2",
          "label": "Type 2 — lumpy, sausage-like",
          "hpi": "Bristol type 2 (lumpy and sausage-like)"
        },
        {
          "value": "3",
          "label": "Type 3 — sausage with cracks",
          "hpi": "Bristol type 3 (cracked sausage)"
        },
        {
          "value": "4",
          "label": "Type 4 — smooth, soft sausage",
          "hpi": "Bristol type 4 (smooth and soft)"
        },
        {
          "value": "5",
          "label": "Type 5 — soft blobs",
          "hpi": "Bristol type 5 (soft blobs)"
        },
        {
          "value": "6",
          "label": "Type 6 — mushy, ragged edges",
          "hpi": "Bristol type 6 (mushy)"
        },
        {
          "value": "7",
          "label": "Type 7 — watery, no solids",
          "hpi": "Bristol type 7 (watery)"
        }
      ]
    },
    "co_straining": {
      "id": "co_straining",
      "text": "Do you strain or spend a long time trying to pass stool?",
      "type": "yes_no",
      "options": []
    },
    "co_incomplete": {
      "id": "co_incomplete",
      "text": "Do you feel you haven't fully emptied?",
      "type": "yes_no",
      "options": []
    },
    "co_digitation": {
      "id": "co_digitation",
      "text": "Do you use a finger or water jet to pass stool?",
      "type": "yes_no",
      "options": []
    },
    "co_pain_passing": {
      "id": "co_pain_passing",
      "text": "Is it painful to pass stool?",
      "type": "yes_no",
      "options": []
    },
    "co_blood": {
      "id": "co_blood",
      "text": "Is there blood in your stool?",
      "type": "yes_no",
      "options": []
    },
    "co_laxatives": {
      "id": "co_laxatives",
      "text": "Do you take medicines to pass stool?",
      "type": "yes_no",
      "options": []
    },
    "jy_duration": {
      "id": "jy_duration",
      "text": "How long have you been yellow?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1w",
          "label": "Less than a week",
          "hpi": "less than a week"
        },
        {
          "value": "1_4w",
          "label": "1–4 weeks",
          "hpi": "one to four weeks"
        },
        {
          "value": "gt_1m",
          "label": "More than a month",
          "hpi": "more than a month"
        }
      ]
    },
    "jy_urine": {
      "id": "jy_urine",
      "text": "What colour is your urine?",
      "type": "single_choice",
      "options": [
        {
          "value": "normal",
          "label": "Normal",
          "hpi": "normal"
        },
        {
          "value": "dark_yellow",
          "label": "Dark yellow",
          "hpi": "dark yellow"
        },
        {
          "value": "brown",
          "label": "Brown",
          "hpi": "brown"
        }
      ]
    },
    "jy_pale_stool": {
      "id": "jy_pale_stool",
      "text": "Are your stools pale or clay-coloured?",
      "type": "yes_no",
      "options": []
    },
    "jy_itching": {
      "id": "jy_itching",
      "text": "Do you have itching of the skin?",
      "type": "yes_no",
      "options": []
    },
    "jy_abd_pain": {
      "id": "jy_abd_pain",
      "text": "Do you have tummy pain with the yellowing?",
      "type": "yes_no",
      "options": []
    },
    "jy_liver_history": {
      "id": "jy_liver_history",
      "text": "Any history of liver disease, hepatitis, or gallstones?",
      "type": "yes_no",
      "options": []
    },
    "jy_risk_exposure": {
      "id": "jy_risk_exposure",
      "text": "Any injections, tattoos, or blood transfusions?",
      "type": "yes_no",
      "options": []
    },
    "jy_new_meds_herbal": {
      "id": "jy_new_meds_herbal",
      "text": "Any new medicines or herbal supplements?",
      "type": "yes_no",
      "options": []
    },
    "rb_duration": {
      "id": "rb_duration",
      "text": "How long have you noticed bleeding from the back passage?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1w",
          "label": "Less than a week",
          "hpi": "less than a week"
        },
        {
          "value": "1_4w",
          "label": "1–4 weeks",
          "hpi": "one to four weeks"
        },
        {
          "value": "gt_1m",
          "label": "More than a month",
          "hpi": "more than a month"
        }
      ]
    },
    "rb_colour": {
      "id": "rb_colour",
      "text": "What colour is the blood?",
      "type": "single_choice",
      "options": [
        {
          "value": "bright_red",
          "label": "Bright red",
          "hpi": "bright-red blood"
        },
        {
          "value": "dark",
          "label": "Dark / maroon",
          "hpi": "dark blood"
        },
        {
          "value": "mixed_in_stool",
          "label": "Mixed in the stool",
          "hpi": "blood mixed in the stool"
        }
      ]
    },
    "rb_relation": {
      "id": "rb_relation",
      "text": "When do you see the blood?",
      "type": "single_choice",
      "options": [
        {
          "value": "on_paper",
          "label": "Only on the toilet paper",
          "hpi": "on wiping"
        },
        {
          "value": "dripping",
          "label": "Dripping into the pan",
          "hpi": "dripping into the pan"
        },
        {
          "value": "mixed_with_stool",
          "label": "Mixed with the stool",
          "hpi": "mixed with stool"
        },
        {
          "value": "after_stool",
          "label": "After passing stool",
          "hpi": "after defecation"
        }
      ]
    },
    "rb_pain": {
      "id": "rb_pain",
      "text": "Is passing stool painful?",
      "type": "yes_no",
      "options": []
    },
    "rb_lump": {
      "id": "rb_lump",
      "text": "Do you feel a lump coming out of the back passage?",
      "type": "yes_no",
      "options": []
    },
    "rb_bowel_change": {
      "id": "rb_bowel_change",
      "text": "Has your bowel habit changed recently?",
      "type": "yes_no",
      "options": []
    },
    "rb_mucus": {
      "id": "rb_mucus",
      "text": "Is there mucus or slime with the blood?",
      "type": "yes_no",
      "options": []
    },
    "pa_duration": {
      "id": "pa_duration",
      "text": "How long have you had the perianal problem?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1w",
          "label": "Less than a week",
          "hpi": "less than a week"
        },
        {
          "value": "1_4w",
          "label": "1–4 weeks",
          "hpi": "one to four weeks"
        },
        {
          "value": "gt_1m",
          "label": "More than a month",
          "hpi": "more than a month"
        }
      ]
    },
    "pa_main": {
      "id": "pa_main",
      "text": "What is the main problem around the back passage?",
      "type": "single_choice",
      "options": [
        {
          "value": "pain",
          "label": "Pain",
          "hpi": "perianal pain"
        },
        {
          "value": "lump",
          "label": "A lump or swelling",
          "hpi": "a perianal lump"
        },
        {
          "value": "discharge",
          "label": "Discharge or pus",
          "hpi": "perianal discharge"
        },
        {
          "value": "itching",
          "label": "Itching",
          "hpi": "perianal itching"
        }
      ]
    },
    "pa_pain_defecation": {
      "id": "pa_pain_defecation",
      "text": "Is it very painful to pass stool?",
      "type": "yes_no",
      "options": []
    },
    "pa_swelling": {
      "id": "pa_swelling",
      "text": "Is there a tender swelling you can feel?",
      "type": "yes_no",
      "options": []
    },
    "pa_discharge": {
      "id": "pa_discharge",
      "text": "Is there pus or discharge?",
      "type": "yes_no",
      "options": []
    },
    "pa_bleeding": {
      "id": "pa_bleeding",
      "text": "Is there any bleeding?",
      "type": "yes_no",
      "options": []
    },
    "pa_recurrent": {
      "id": "pa_recurrent",
      "text": "Has this happened before, or does it keep coming back?",
      "type": "yes_no",
      "options": []
    },
    "fi_duration": {
      "id": "fi_duration",
      "text": "How long have you had trouble controlling your bowels?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1m",
          "label": "Less than a month",
          "hpi": "less than a month"
        },
        {
          "value": "1_6m",
          "label": "1–6 months",
          "hpi": "one to six months"
        },
        {
          "value": "gt_6m",
          "label": "More than 6 months",
          "hpi": "more than six months"
        }
      ]
    },
    "fi_type": {
      "id": "fi_type",
      "text": "What happens?",
      "type": "single_choice",
      "options": [
        {
          "value": "urgency",
          "label": "I cannot reach the toilet in time",
          "hpi": "urge incontinence"
        },
        {
          "value": "passive_leak",
          "label": "It leaks without my knowing",
          "hpi": "passive leakage"
        },
        {
          "value": "with_constipation",
          "label": "Leakage with hard stools / constipation",
          "hpi": "leakage on a background of constipation"
        }
      ]
    },
    "fi_consistency": {
      "id": "fi_consistency",
      "text": "Is the leakage solid, liquid, or both?",
      "type": "single_choice",
      "options": [
        {
          "value": "solid",
          "label": "Solid",
          "hpi": "solid"
        },
        {
          "value": "liquid",
          "label": "Liquid",
          "hpi": "liquid"
        },
        {
          "value": "both",
          "label": "Both",
          "hpi": "solid and liquid"
        }
      ]
    },
    "fi_constipation_hx": {
      "id": "fi_constipation_hx",
      "text": "Do you also get constipated with hard stools?",
      "type": "yes_no",
      "options": []
    },
    "fi_obstetric_surgical": {
      "id": "fi_obstetric_surgical",
      "text": "Have you had a difficult childbirth or surgery near the back passage?",
      "type": "yes_no",
      "options": []
    },
    "fi_blood": {
      "id": "fi_blood",
      "text": "Is there blood with the leakage?",
      "type": "yes_no",
      "options": []
    },
    "bl_duration": {
      "id": "bl_duration",
      "text": "How long have you felt bloated or distended?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1m",
          "label": "Less than a month",
          "hpi": "less than a month"
        },
        {
          "value": "1_6m",
          "label": "1–6 months",
          "hpi": "one to six months"
        },
        {
          "value": "gt_6m",
          "label": "More than 6 months",
          "hpi": "more than six months"
        }
      ]
    },
    "bl_pattern": {
      "id": "bl_pattern",
      "text": "When is the bloating worst?",
      "type": "single_choice",
      "options": [
        {
          "value": "after_meals",
          "label": "After meals",
          "hpi": "after meals"
        },
        {
          "value": "all_day",
          "label": "All day",
          "hpi": "throughout the day"
        },
        {
          "value": "progressive",
          "label": "Getting steadily bigger",
          "hpi": "with progressive distension"
        }
      ]
    },
    "bl_relieved_flatus": {
      "id": "bl_relieved_flatus",
      "text": "Is it relieved by passing wind?",
      "type": "yes_no",
      "options": []
    },
    "bl_relieved_defecation": {
      "id": "bl_relieved_defecation",
      "text": "Is it relieved by passing stool?",
      "type": "yes_no",
      "options": []
    },
    "bl_bowel_change": {
      "id": "bl_bowel_change",
      "text": "Has your bowel habit changed?",
      "type": "yes_no",
      "options": []
    },
    "bl_visible_distension": {
      "id": "bl_visible_distension",
      "text": "Is your tummy visibly swollen?",
      "type": "yes_no",
      "options": []
    },
    "bl_food_relation": {
      "id": "bl_food_relation",
      "text": "Is it worse with wheat or dairy foods?",
      "type": "yes_no",
      "options": []
    },
    "as_duration": {
      "id": "as_duration",
      "text": "How long has your tummy been swollen?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_2w",
          "label": "Less than 2 weeks",
          "hpi": "less than two weeks"
        },
        {
          "value": "2_8w",
          "label": "2–8 weeks",
          "hpi": "two to eight weeks"
        },
        {
          "value": "gt_2m",
          "label": "More than 2 months",
          "hpi": "more than two months"
        }
      ]
    },
    "as_onset": {
      "id": "as_onset",
      "text": "Did the swelling come on gradually or quickly?",
      "type": "single_choice",
      "options": [
        {
          "value": "gradual",
          "label": "Gradually",
          "hpi": "gradual"
        },
        {
          "value": "rapid",
          "label": "Quickly",
          "hpi": "rapid"
        }
      ]
    },
    "as_leg_swelling": {
      "id": "as_leg_swelling",
      "text": "Are your legs or ankles also swollen?",
      "type": "yes_no",
      "options": []
    },
    "as_breathlessness": {
      "id": "as_breathlessness",
      "text": "Are you short of breath?",
      "type": "yes_no",
      "options": []
    },
    "as_liver_history": {
      "id": "as_liver_history",
      "text": "Any history of liver disease or hepatitis?",
      "type": "yes_no",
      "options": []
    },
    "as_known_cancer": {
      "id": "as_known_cancer",
      "text": "Have you ever been diagnosed with cancer?",
      "type": "yes_no",
      "options": []
    },
    "wl_appetite": {
      "id": "wl_appetite",
      "text": "How is your appetite?",
      "type": "single_choice",
      "options": [
        {
          "value": "increased",
          "label": "Increased",
          "hpi": "increased"
        },
        {
          "value": "decreased",
          "label": "Decreased",
          "hpi": "reduced"
        },
        {
          "value": "normal",
          "label": "Normal",
          "hpi": "normal"
        }
      ]
    },
    "wl_heat_intolerance": {
      "id": "wl_heat_intolerance",
      "text": "Do you feel hot, sweaty, or have a racing heart?",
      "type": "yes_no",
      "options": []
    },
    "wl_thirst_polyuria": {
      "id": "wl_thirst_polyuria",
      "text": "Are you very thirsty or passing a lot of urine?",
      "type": "yes_no",
      "options": []
    },
    "wl_bowel_change": {
      "id": "wl_bowel_change",
      "text": "Has your bowel habit changed?",
      "type": "yes_no",
      "options": []
    },
    "wl_chronic_cough": {
      "id": "wl_chronic_cough",
      "text": "Do you have a long-standing cough or night sweats?",
      "type": "yes_no",
      "options": []
    },
    "wl_lump": {
      "id": "wl_lump",
      "text": "Have you noticed any lump or swelling?",
      "type": "yes_no",
      "options": []
    },
    "an_duration": {
      "id": "an_duration",
      "text": "How long have you felt tired or looked pale?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1m",
          "label": "Less than a month",
          "hpi": "less than a month"
        },
        {
          "value": "1_6m",
          "label": "1–6 months",
          "hpi": "one to six months"
        },
        {
          "value": "gt_6m",
          "label": "More than 6 months",
          "hpi": "more than six months"
        }
      ]
    },
    "an_exertional_breathless": {
      "id": "an_exertional_breathless",
      "text": "Do you get breathless on exertion?",
      "type": "yes_no",
      "options": []
    },
    "an_pica": {
      "id": "an_pica",
      "text": "Do you crave or chew ice, mud, or other unusual things?",
      "type": "yes_no",
      "options": []
    },
    "an_menorrhagia": {
      "id": "an_menorrhagia",
      "text": "If female: are your periods heavy?",
      "type": "yes_no",
      "options": []
    },
    "an_abdo_pain": {
      "id": "an_abdo_pain",
      "text": "Do you have any tummy pain or indigestion?",
      "type": "yes_no",
      "options": []
    },
    "an_bowel_change": {
      "id": "an_bowel_change",
      "text": "Has your bowel habit changed?",
      "type": "yes_no",
      "options": []
    },
    "ao_duration": {
      "id": "ao_duration",
      "text": "How long have you had poor appetite?",
      "type": "single_choice",
      "options": [
        {
          "value": "lt_1m",
          "label": "Less than a month",
          "hpi": "less than a month"
        },
        {
          "value": "1_6m",
          "label": "1–6 months",
          "hpi": "one to six months"
        },
        {
          "value": "gt_6m",
          "label": "More than 6 months",
          "hpi": "more than six months"
        }
      ]
    },
    "ao_early_satiety": {
      "id": "ao_early_satiety",
      "text": "Do you feel full after only a few bites?",
      "type": "yes_no",
      "options": []
    },
    "ao_meat_aversion": {
      "id": "ao_meat_aversion",
      "text": "Have you gone off meat or rich foods?",
      "type": "yes_no",
      "options": []
    },
    "ao_nausea": {
      "id": "ao_nausea",
      "text": "Do you feel sick (nauseated)?",
      "type": "yes_no",
      "options": []
    },
    "ao_abdo_pain": {
      "id": "ao_abdo_pain",
      "text": "Do you have tummy pain?",
      "type": "yes_no",
      "options": []
    },
    "ao_low_mood": {
      "id": "ao_low_mood",
      "text": "Have you been feeling low, sad, or losing interest in things?",
      "type": "yes_no",
      "options": []
    },
    "gen_menstruation": {
      "id": "gen_menstruation",
      "text": "If female: are your periods normal?",
      "type": "single_choice",
      "options": [
        {
          "value": "normal",
          "label": "Normal"
        },
        {
          "value": "irregular",
          "label": "Irregular"
        },
        {
          "value": "menopause",
          "label": "Reached menopause"
        },
        {
          "value": "na",
          "label": "Not applicable"
        }
      ]
    },
    "gen_weight_loss": {
      "id": "gen_weight_loss",
      "text": "Have you lost weight without trying?",
      "type": "yes_no",
      "options": []
    },
    "gen_weight_loss_kg": {
      "id": "gen_weight_loss_kg",
      "text": "About how many kilograms have you lost?",
      "type": "number",
      "options": []
    },
    "gen_weight_loss_months": {
      "id": "gen_weight_loss_months",
      "text": "Over how many months?",
      "type": "number",
      "options": []
    },
    "gen_black_stool": {
      "id": "gen_black_stool",
      "text": "Have you passed black, tarry stools?",
      "type": "yes_no",
      "options": []
    },
    "gen_haematemesis": {
      "id": "gen_haematemesis",
      "text": "Have you vomited blood?",
      "type": "yes_no",
      "options": []
    },
    "gen_fresh_blood": {
      "id": "gen_fresh_blood",
      "text": "Have you seen fresh red blood in your stool?",
      "type": "yes_no",
      "options": []
    },
    "gen_fever": {
      "id": "gen_fever",
      "text": "Do you have fever?",
      "type": "yes_no",
      "options": []
    },
    "gen_fever_days": {
      "id": "gen_fever_days",
      "text": "For how many days?",
      "type": "number",
      "options": []
    },
    "gen_comorbidities": {
      "id": "gen_comorbidities",
      "text": "Do you have any of these conditions? (choose any)",
      "type": "multi_choice",
      "options": [
        {
          "value": "diabetes",
          "label": "Diabetes"
        },
        {
          "value": "hypertension",
          "label": "High blood pressure"
        },
        {
          "value": "heart_disease",
          "label": "Heart disease"
        },
        {
          "value": "asthma",
          "label": "Asthma"
        },
        {
          "value": "none",
          "label": "None"
        }
      ]
    },
    "gen_surgery": {
      "id": "gen_surgery",
      "text": "Have you had any surgery?",
      "type": "yes_no",
      "options": []
    },
    "gen_surgery_detail": {
      "id": "gen_surgery_detail",
      "text": "Which surgery, and when?",
      "type": "text",
      "options": []
    },
    "gen_alcohol": {
      "id": "gen_alcohol",
      "text": "Do you drink alcohol?",
      "type": "yes_no",
      "options": []
    },
    "gen_alcohol_detail": {
      "id": "gen_alcohol_detail",
      "text": "Which type, and how much per week?",
      "type": "text",
      "options": []
    },
    "gen_smoking": {
      "id": "gen_smoking",
      "text": "Do you smoke?",
      "type": "single_choice",
      "options": [
        {
          "value": "none",
          "label": false
        },
        {
          "value": "bidi",
          "label": "Bidi"
        },
        {
          "value": "cigarette",
          "label": "Cigarette"
        }
      ]
    },
    "gen_smoking_count": {
      "id": "gen_smoking_count",
      "text": "How many per day?",
      "type": "number",
      "options": []
    },
    "gen_exercise": {
      "id": "gen_exercise",
      "text": "Do you exercise regularly?",
      "type": "yes_no",
      "options": []
    },
    "gen_diet": {
      "id": "gen_diet",
      "text": "What is your diet?",
      "type": "single_choice",
      "options": [
        {
          "value": "vegetarian",
          "label": "Vegetarian"
        },
        {
          "value": "mixed",
          "label": "Mixed"
        },
        {
          "value": "mostly_nonveg",
          "label": "Mostly non-vegetarian"
        }
      ]
    },
    "gen_regular_meds": {
      "id": "gen_regular_meds",
      "text": "Do you take any of these regularly? (choose any)",
      "type": "multi_choice",
      "options": [
        {
          "value": "painkillers",
          "label": "Painkillers"
        },
        {
          "value": "antacids",
          "label": "Antacids"
        },
        {
          "value": "blood_thinners",
          "label": "Blood thinners"
        },
        {
          "value": "other",
          "label": "Other"
        },
        {
          "value": "none",
          "label": "None"
        }
      ]
    },
    "gen_previous_tests": {
      "id": "gen_previous_tests",
      "text": "Have you had any blood tests or scans recently?",
      "type": "yes_no",
      "options": []
    },
    "gen_stress": {
      "id": "gen_stress",
      "text": "Do you have a lot of stress or anxiety?",
      "type": "yes_no",
      "options": []
    },
    "gen_palpitations": {
      "id": "gen_palpitations",
      "text": "Do you get palpitations (a racing heartbeat)?",
      "type": "yes_no",
      "options": []
    },
    "gen_fatigue": {
      "id": "gen_fatigue",
      "text": "Do you feel unusually tired or weak?",
      "type": "yes_no",
      "options": []
    }
  },
  "flows": {
    "abdominal_pain": {
      "start": "ap_duration",
      "transitions": {
        "ap_duration": {
          "default": "ap_site"
        },
        "ap_site": {
          "default": "ap_character"
        },
        "ap_character": {
          "default": "ap_radiation"
        },
        "ap_radiation": {
          "default": "ap_pattern"
        },
        "ap_pattern": {
          "default": "ap_meals"
        },
        "ap_meals": {
          "default": "ap_night"
        }
      }
    },
    "heartburn": {
      "start": "hb_duration",
      "transitions": {
        "hb_duration": {
          "default": "hb_location"
        },
        "hb_location": {
          "default": "hb_rising"
        },
        "hb_rising": {
          "default": "hb_taste"
        },
        "hb_taste": {
          "default": "hb_timing"
        },
        "hb_timing": {
          "default": "hb_triggers"
        },
        "hb_triggers": {
          "default": "hb_frequency"
        },
        "hb_frequency": {
          "default": "hb_sleep"
        },
        "hb_sleep": {
          "default": "hb_cough_voice"
        },
        "hb_cough_voice": {
          "default": "hb_chest_pain"
        },
        "hb_chest_pain": {
          "yes": "hb_chest_pain_radiate",
          "default": "hb_tried_meds"
        },
        "hb_chest_pain_radiate": {
          "default": "hb_tried_meds"
        },
        "hb_tried_meds": {
          "yes": "hb_meds_helped",
          "default": "hb_prior_scope"
        },
        "hb_meds_helped": {
          "default": "hb_prior_scope"
        }
      }
    },
    "dysphagia": {
      "start": "dys_duration",
      "transitions": {
        "dys_duration": {
          "default": "dys_type"
        },
        "dys_type": {
          "default": "dys_consistency"
        },
        "dys_consistency": {
          "default": "dys_progression"
        },
        "dys_progression": {
          "default": "dys_onset"
        },
        "dys_onset": {
          "default": "dys_regurg"
        },
        "dys_regurg": {
          "default": "dys_reflux"
        },
        "dys_reflux": {
          "default": "dys_aspiration"
        },
        "dys_aspiration": {
          "default": "dys_voice"
        },
        "dys_voice": {
          "default": "dys_radiation_hx"
        },
        "dys_radiation_hx": {
          "default": "dys_corrosive"
        }
      }
    },
    "nausea_vomiting": {
      "start": "nv_duration",
      "transitions": {
        "nv_duration": {
          "default": "nv_vomit_content"
        },
        "nv_vomit_content": {
          "default": "nv_timing"
        },
        "nv_timing": {
          "default": "nv_abd_pain"
        },
        "nv_abd_pain": {
          "default": "nv_new_meds"
        },
        "nv_new_meds": {
          "default": "nv_travel_diet"
        }
      }
    },
    "dyspepsia": {
      "start": "dy_duration",
      "transitions": {
        "dy_duration": {
          "default": "dy_relation"
        },
        "dy_relation": {
          "default": "dy_food_triggers"
        },
        "dy_food_triggers": {
          "default": "dy_antacid_relief"
        },
        "dy_antacid_relief": {
          "default": "dy_stool_relief"
        },
        "dy_stool_relief": {
          "default": "dy_bloating"
        }
      }
    },
    "belching": {
      "start": "be_duration",
      "transitions": {
        "be_duration": {
          "default": "be_timing"
        },
        "be_timing": {
          "default": "be_fizzy_fast_stress"
        },
        "be_fizzy_fast_stress": {
          "default": "be_food_triggers"
        },
        "be_food_triggers": {
          "default": "be_flatulence"
        }
      }
    },
    "diarrhoea": {
      "start": "di_duration",
      "transitions": {
        "di_duration": {
          "default": "di_frequency"
        },
        "di_frequency": {
          "default": "di_consistency"
        },
        "di_consistency": {
          "default": "di_blood"
        },
        "di_blood": {
          "default": "di_mucus"
        },
        "di_mucus": {
          "default": "di_nocturnal"
        },
        "di_nocturnal": {
          "default": "di_relieved_by_defecation"
        },
        "di_relieved_by_defecation": {
          "default": "di_recent_travel"
        },
        "di_recent_travel": {
          "default": "di_recent_antibiotics"
        }
      }
    },
    "constipation": {
      "start": "co_duration",
      "transitions": {
        "co_duration": {
          "default": "co_frequency"
        },
        "co_frequency": {
          "default": "co_urge"
        },
        "co_urge": {
          "default": "co_timing"
        },
        "co_timing": {
          "default": "co_bristol"
        },
        "co_bristol": {
          "default": "co_straining"
        },
        "co_straining": {
          "default": "co_incomplete"
        },
        "co_incomplete": {
          "default": "co_digitation"
        },
        "co_digitation": {
          "default": "co_pain_passing"
        },
        "co_pain_passing": {
          "default": "co_blood"
        },
        "co_blood": {
          "default": "co_laxatives"
        }
      }
    },
    "jaundice": {
      "start": "jy_duration",
      "transitions": {
        "jy_duration": {
          "default": "jy_urine"
        },
        "jy_urine": {
          "default": "jy_pale_stool"
        },
        "jy_pale_stool": {
          "default": "jy_itching"
        },
        "jy_itching": {
          "default": "jy_abd_pain"
        },
        "jy_abd_pain": {
          "default": "jy_liver_history"
        },
        "jy_liver_history": {
          "default": "jy_risk_exposure"
        },
        "jy_risk_exposure": {
          "default": "jy_new_meds_herbal"
        }
      }
    },
    "rectal_bleeding": {
      "start": "rb_duration",
      "transitions": {
        "rb_duration": {
          "default": "rb_colour"
        },
        "rb_colour": {
          "default": "rb_relation"
        },
        "rb_relation": {
          "default": "rb_pain"
        },
        "rb_pain": {
          "default": "rb_lump"
        },
        "rb_lump": {
          "default": "rb_bowel_change"
        },
        "rb_bowel_change": {
          "default": "rb_mucus"
        }
      }
    },
    "perianal": {
      "start": "pa_duration",
      "transitions": {
        "pa_duration": {
          "default": "pa_main"
        },
        "pa_main": {
          "default": "pa_pain_defecation"
        },
        "pa_pain_defecation": {
          "default": "pa_swelling"
        },
        "pa_swelling": {
          "default": "pa_discharge"
        },
        "pa_discharge": {
          "default": "pa_bleeding"
        },
        "pa_bleeding": {
          "default": "pa_recurrent"
        }
      }
    },
    "faecal_incontinence": {
      "start": "fi_duration",
      "transitions": {
        "fi_duration": {
          "default": "fi_type"
        },
        "fi_type": {
          "default": "fi_consistency"
        },
        "fi_consistency": {
          "default": "fi_constipation_hx"
        },
        "fi_constipation_hx": {
          "default": "fi_obstetric_surgical"
        },
        "fi_obstetric_surgical": {
          "default": "fi_blood"
        }
      }
    },
    "bloating": {
      "start": "bl_duration",
      "transitions": {
        "bl_duration": {
          "default": "bl_pattern"
        },
        "bl_pattern": {
          "default": "bl_relieved_flatus"
        },
        "bl_relieved_flatus": {
          "default": "bl_relieved_defecation"
        },
        "bl_relieved_defecation": {
          "default": "bl_bowel_change"
        },
        "bl_bowel_change": {
          "default": "bl_visible_distension"
        },
        "bl_visible_distension": {
          "default": "bl_food_relation"
        }
      }
    },
    "ascites": {
      "start": "as_duration",
      "transitions": {
        "as_duration": {
          "default": "as_onset"
        },
        "as_onset": {
          "default": "as_leg_swelling"
        },
        "as_leg_swelling": {
          "default": "as_breathlessness"
        },
        "as_breathlessness": {
          "default": "as_liver_history"
        },
        "as_liver_history": {
          "default": "as_known_cancer"
        }
      }
    },
    "weight_loss": {
      "start": "wl_appetite",
      "transitions": {
        "wl_appetite": {
          "default": "wl_heat_intolerance"
        },
        "wl_heat_intolerance": {
          "default": "wl_thirst_polyuria"
        },
        "wl_thirst_polyuria": {
          "default": "wl_bowel_change"
        },
        "wl_bowel_change": {
          "default": "wl_chronic_cough"
        },
        "wl_chronic_cough": {
          "default": "wl_lump"
        }
      }
    },
    "anaemia": {
      "start": "an_duration",
      "transitions": {
        "an_duration": {
          "default": "an_exertional_breathless"
        },
        "an_exertional_breathless": {
          "default": "an_pica"
        },
        "an_pica": {
          "default": "an_menorrhagia"
        },
        "an_menorrhagia": {
          "default": "an_abdo_pain"
        },
        "an_abdo_pain": {
          "default": "an_bowel_change"
        }
      }
    },
    "anorexia": {
      "start": "ao_duration",
      "transitions": {
        "ao_duration": {
          "default": "ao_early_satiety"
        },
        "ao_early_satiety": {
          "default": "ao_meat_aversion"
        },
        "ao_meat_aversion": {
          "default": "ao_nausea"
        },
        "ao_nausea": {
          "default": "ao_abdo_pain"
        },
        "ao_abdo_pain": {
          "default": "ao_low_mood"
        }
      }
    },
    "general": {
      "start": "gen_menstruation",
      "transitions": {
        "gen_menstruation": {
          "default": "gen_weight_loss"
        },
        "gen_weight_loss": {
          "yes": "gen_weight_loss_kg",
          "default": "gen_black_stool"
        },
        "gen_weight_loss_kg": {
          "default": "gen_weight_loss_months"
        },
        "gen_weight_loss_months": {
          "default": "gen_black_stool"
        },
        "gen_black_stool": {
          "default": "gen_haematemesis"
        },
        "gen_haematemesis": {
          "default": "gen_fresh_blood"
        },
        "gen_fresh_blood": {
          "default": "gen_fever"
        },
        "gen_fever": {
          "yes": "gen_fever_days",
          "default": "gen_comorbidities"
        },
        "gen_fever_days": {
          "default": "gen_comorbidities"
        },
        "gen_comorbidities": {
          "default": "gen_surgery"
        },
        "gen_surgery": {
          "yes": "gen_surgery_detail",
          "default": "gen_alcohol"
        },
        "gen_surgery_detail": {
          "default": "gen_alcohol"
        },
        "gen_alcohol": {
          "yes": "gen_alcohol_detail",
          "default": "gen_smoking"
        },
        "gen_alcohol_detail": {
          "default": "gen_smoking"
        },
        "gen_smoking": {
          "none": "gen_exercise",
          "default": "gen_smoking_count"
        },
        "gen_smoking_count": {
          "default": "gen_exercise"
        },
        "gen_exercise": {
          "default": "gen_diet"
        },
        "gen_diet": {
          "default": "gen_regular_meds"
        },
        "gen_regular_meds": {
          "default": "gen_previous_tests"
        },
        "gen_previous_tests": {
          "default": "gen_stress"
        },
        "gen_stress": {
          "default": "gen_palpitations"
        },
        "gen_palpitations": {
          "default": "gen_fatigue"
        }
      }
    }
  }
};
