// Generated by webapp/build_kg_json.py — do not edit by hand.
window.KG_DATA = {
  "version": "v1",
  "entry_question": "q_main_complaint",
  "questions": {
    "q_main_complaint": {
      "id": "q_main_complaint",
      "text": "What is your main problem today?",
      "type": "single_choice",
      "options": [
        {
          "value": "abdominal_pain",
          "label": "Abdominal Pain"
        },
        {
          "value": "bloating",
          "label": "Bloating"
        },
        {
          "value": "heartburn",
          "label": "Heartburn"
        }
      ]
    },
    "q_location": {
      "id": "q_location",
      "text": "Where is the pain located?",
      "type": "single_choice",
      "options": [
        {
          "value": "ruq",
          "label": "Right Upper Abdomen"
        },
        {
          "value": "epigastric",
          "label": "Upper Middle Abdomen"
        },
        {
          "value": "rlq",
          "label": "Right Lower Abdomen"
        },
        {
          "value": "diffuse",
          "label": "Entire Abdomen"
        }
      ]
    },
    "q_fatty_food": {
      "id": "q_fatty_food",
      "text": "Does the pain worsen after fatty meals?",
      "type": "yes_no",
      "options": []
    },
    "q_heartburn": {
      "id": "q_heartburn",
      "text": "Do you experience burning behind the chest?",
      "type": "yes_no",
      "options": []
    },
    "q_jaundice": {
      "id": "q_jaundice",
      "text": "Have you noticed yellowing of the eyes or skin?",
      "type": "yes_no",
      "options": []
    },
    "q_fever": {
      "id": "q_fever",
      "text": "Do you have fever?",
      "type": "yes_no",
      "options": []
    },
    "q_weight_loss": {
      "id": "q_weight_loss",
      "text": "Have you lost weight unintentionally?",
      "type": "yes_no",
      "options": []
    },
    "q_black_stool": {
      "id": "q_black_stool",
      "text": "Have you passed black stools?",
      "type": "yes_no",
      "options": []
    },
    "q_diarrhea": {
      "id": "q_diarrhea",
      "text": "Do you have diarrhea?",
      "type": "yes_no",
      "options": []
    },
    "q_constipation": {
      "id": "q_constipation",
      "text": "Do you have constipation?",
      "type": "yes_no",
      "options": []
    }
  },
  "flows": {
    "abdominal_pain": {
      "start": "q_location",
      "transitions": {
        "q_location": {
          "ruq": "q_fatty_food",
          "epigastric": "q_heartburn",
          "rlq": "q_fever",
          "diffuse": "q_diarrhea"
        },
        "q_fatty_food": {
          "yes": "q_jaundice",
          "no": "q_fever"
        },
        "q_jaundice": {
          "yes": "q_fever",
          "no": "q_fever"
        },
        "q_heartburn": {
          "yes": "q_weight_loss",
          "no": "q_black_stool"
        },
        "q_diarrhea": {
          "yes": "q_weight_loss",
          "no": "q_constipation"
        }
      }
    }
  }
};
