"""Export a knowledge graph's questionnaire (questions + flows) for the browser.

The patient web app runs the questionnaire entirely client-side, so it needs the
question metadata and branching logic as static data. This script reuses the
existing loader (single source of truth) and emits:

  webapp/patient/kg-data.js    -> window.KG_DATA = {...}   (loaded via <script>)
  webapp/patient/kg-data.json  -> the same payload as plain JSON (reference/API)

Only questionnaire data is exported. Clinical scoring/ranking stays in the Python
pipeline on the doctor's side.

Usage:
    python webapp/build_kg_json.py --kg-version v1
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from cdss.knowledge import KnowledgeGraph

OUT_DIR = ROOT / "webapp" / "patient"


def build_payload(version: str) -> dict:
    kg = KnowledgeGraph.load(ROOT / "knowledge_graph" / version)

    questions = {
        qid: {
            "id": q.id,
            "text": q.text,
            "type": q.type,
            "options": list(q.options),
        }
        for qid, q in kg.questions.items()
    }

    flows = {
        fid: {"start": flow.start, "transitions": _normalize_transitions(flow.transitions)}
        for fid, flow in kg.flows.items()
    }

    return {
        "version": kg.version,
        "entry_question": _entry_question(kg),
        "questions": questions,
        "flows": flows,
    }


# YAML parses bare `yes:`/`no:` mapping keys as booleans, which the loader then
# stringifies to "True"/"False". Normalize them back to the "yes"/"no" answer keys
# the browser emits (and that the Python conditions expect, e.g. q_x == 'yes').
_ANSWER_KEY_FIXUPS = {"true": "yes", "false": "no"}


def _normalize_transitions(transitions: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    return {
        source: {_normalize_answer_key(answer): target for answer, target in branches.items()}
        for source, branches in transitions.items()
    }


def _normalize_answer_key(answer: str) -> str:
    lowered = str(answer).strip().lower()
    return _ANSWER_KEY_FIXUPS.get(lowered, lowered)


def _entry_question(kg: KnowledgeGraph) -> str | None:
    """The first question shown. q_main_complaint routes into a flow by its answer;
    otherwise fall back to the first flow's start question."""
    if "q_main_complaint" in kg.questions:
        return "q_main_complaint"
    for flow in kg.flows.values():
        if flow.start:
            return flow.start
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Export KG questionnaire data for the browser.")
    parser.add_argument("--kg-version", default="v1", help="Knowledge graph version to export.")
    args = parser.parse_args()

    payload = build_payload(args.kg_version)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    json_text = json.dumps(payload, indent=2, ensure_ascii=False)
    (OUT_DIR / "kg-data.json").write_text(json_text + "\n", encoding="utf-8")
    (OUT_DIR / "kg-data.js").write_text(
        "// Generated by webapp/build_kg_json.py — do not edit by hand.\n"
        f"window.KG_DATA = {json_text};\n",
        encoding="utf-8",
    )

    print(f"Exported {args.kg_version}: {len(payload['questions'])} questions, "
          f"{len(payload['flows'])} flow(s), entry='{payload['entry_question']}'")
    print(f"  -> {OUT_DIR / 'kg-data.js'}")
    print(f"  -> {OUT_DIR / 'kg-data.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
