"""Export the doctor registry (slug + display name) for the browser.

The patient web app reads the doctor slug from its URL and shows the doctor's name.
It must NEVER see credentials, so this script emits only the public fields — slug and
name — from doctors/doctors.yaml:

  webapp/patient/doctors.js    -> window.DOCTORS = {...}   (loaded via <script>)
  webapp/patient/doctors.json  -> the same payload as plain JSON (reference)

Emails, passwords, receptionist addresses, and dashboard hashes stay server-side in
doctors/<slug>.yaml and are never exported here.

Usage:
    python webapp/build_doctors_js.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "doctors" / "doctors.yaml"
OUT_DIR = ROOT / "webapp" / "patient"


def build_payload() -> dict:
    if not REGISTRY.exists():
        raise SystemExit(
            f"Doctor registry not found: {REGISTRY}\n"
            "Create it (see doctors/doctors.example.yaml)."
        )
    raw = yaml.safe_load(REGISTRY.read_text(encoding="utf-8")) or []
    doctors: dict[str, dict] = {}
    for entry in raw:
        slug = str(entry.get("slug", "")).strip().lower()
        name = str(entry.get("name", "")).strip()
        if not slug or not name:
            raise SystemExit(f"Every registry entry needs a slug and a name; got: {entry!r}")
        if slug in doctors:
            raise SystemExit(f"Duplicate slug in registry: {slug!r}")
        doctors[slug] = {"name": name}
    return doctors


def main() -> int:
    doctors = build_payload()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    json_text = json.dumps(doctors, indent=2, ensure_ascii=False)
    (OUT_DIR / "doctors.json").write_text(json_text + "\n", encoding="utf-8")
    (OUT_DIR / "doctors.js").write_text(
        "// Generated by webapp/build_doctors_js.py — do not edit by hand.\n"
        "// Public data only (slug + name). Credentials live server-side in doctors/.\n"
        f"window.DOCTORS = {json_text};\n",
        encoding="utf-8",
    )

    print(f"Exported {len(doctors)} doctor(s): {', '.join(doctors)}")
    print(f"  -> {OUT_DIR / 'doctors.js'}")
    print(f"  -> {OUT_DIR / 'doctors.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
